// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: bin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinStatus int32

const (
	BinStatus_pending   BinStatus = 0
	BinStatus_delivered BinStatus = 1
)

// Enum value maps for BinStatus.
var (
	BinStatus_name = map[int32]string{
		0: "pending",
		1: "delivered",
	}
	BinStatus_value = map[string]int32{
		"pending":   0,
		"delivered": 1,
	}
)

func (x BinStatus) Enum() *BinStatus {
	p := new(BinStatus)
	*p = x
	return p
}

func (x BinStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BinStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bin_proto_enumTypes[0].Descriptor()
}

func (BinStatus) Type() protoreflect.EnumType {
	return &file_bin_proto_enumTypes[0]
}

func (x BinStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BinStatus.Descriptor instead.
func (BinStatus) EnumDescriptor() ([]byte, []int) {
	return file_bin_proto_rawDescGZIP(), []int{0}
}

type BinType int32

const (
	BinType_large  BinType = 0
	BinType_medium BinType = 1
	BinType_small  BinType = 2
)

// Enum value maps for BinType.
var (
	BinType_name = map[int32]string{
		0: "large",
		1: "medium",
		2: "small",
	}
	BinType_value = map[string]int32{
		"large":  0,
		"medium": 1,
		"small":  2,
	}
)

func (x BinType) Enum() *BinType {
	p := new(BinType)
	*p = x
	return p
}

func (x BinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BinType) Descriptor() protoreflect.EnumDescriptor {
	return file_bin_proto_enumTypes[1].Descriptor()
}

func (BinType) Type() protoreflect.EnumType {
	return &file_bin_proto_enumTypes[1]
}

func (x BinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BinType.Descriptor instead.
func (BinType) EnumDescriptor() ([]byte, []int) {
	return file_bin_proto_rawDescGZIP(), []int{1}
}

type Bin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status BinStatus `protobuf:"varint,2,opt,name=status,proto3,enum=pb.BinStatus" json:"status,omitempty"`
	Type   BinType   `protobuf:"varint,3,opt,name=type,proto3,enum=pb.BinType" json:"type,omitempty"`
}

func (x *Bin) Reset() {
	*x = Bin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bin) ProtoMessage() {}

func (x *Bin) ProtoReflect() protoreflect.Message {
	mi := &file_bin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bin.ProtoReflect.Descriptor instead.
func (*Bin) Descriptor() ([]byte, []int) {
	return file_bin_proto_rawDescGZIP(), []int{0}
}

func (x *Bin) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bin) GetStatus() BinStatus {
	if x != nil {
		return x.Status
	}
	return BinStatus_pending
}

func (x *Bin) GetType() BinType {
	if x != nil {
		return x.Type
	}
	return BinType_large
}

var File_bin_proto protoreflect.FileDescriptor

var file_bin_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x5d, 0x0a, 0x03, 0x42, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x27,
	0x0a, 0x09, 0x42, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x70,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x65, 0x64, 0x10, 0x01, 0x2a, 0x2b, 0x0a, 0x07, 0x42, 0x69, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x73, 0x6d, 0x61,
	0x6c, 0x6c, 0x10, 0x02, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2d, 0x63, 0x6f,
	0x64, 0x65, 0x73, 0x2f, 0x77, 0x61, 0x73, 0x74, 0x65, 0x2d, 0x62, 0x69, 0x6e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bin_proto_rawDescOnce sync.Once
	file_bin_proto_rawDescData = file_bin_proto_rawDesc
)

func file_bin_proto_rawDescGZIP() []byte {
	file_bin_proto_rawDescOnce.Do(func() {
		file_bin_proto_rawDescData = protoimpl.X.CompressGZIP(file_bin_proto_rawDescData)
	})
	return file_bin_proto_rawDescData
}

var file_bin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bin_proto_goTypes = []interface{}{
	(BinStatus)(0), // 0: pb.BinStatus
	(BinType)(0),   // 1: pb.BinType
	(*Bin)(nil),    // 2: pb.Bin
}
var file_bin_proto_depIdxs = []int32{
	0, // 0: pb.Bin.status:type_name -> pb.BinStatus
	1, // 1: pb.Bin.type:type_name -> pb.BinType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bin_proto_init() }
func file_bin_proto_init() {
	if File_bin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bin_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bin_proto_goTypes,
		DependencyIndexes: file_bin_proto_depIdxs,
		EnumInfos:         file_bin_proto_enumTypes,
		MessageInfos:      file_bin_proto_msgTypes,
	}.Build()
	File_bin_proto = out.File
	file_bin_proto_rawDesc = nil
	file_bin_proto_goTypes = nil
	file_bin_proto_depIdxs = nil
}
