// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: rpc_request.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type REQUEST_STATE int32

const (
	REQUEST_STATE_pendingA REQUEST_STATE = 0
	REQUEST_STATE_success  REQUEST_STATE = 1
	REQUEST_STATE_failed   REQUEST_STATE = 2
)

// Enum value maps for REQUEST_STATE.
var (
	REQUEST_STATE_name = map[int32]string{
		0: "pendingA",
		1: "success",
		2: "failed",
	}
	REQUEST_STATE_value = map[string]int32{
		"pendingA": 0,
		"success":  1,
		"failed":   2,
	}
)

func (x REQUEST_STATE) Enum() *REQUEST_STATE {
	p := new(REQUEST_STATE)
	*p = x
	return p
}

func (x REQUEST_STATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (REQUEST_STATE) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_request_proto_enumTypes[0].Descriptor()
}

func (REQUEST_STATE) Type() protoreflect.EnumType {
	return &file_rpc_request_proto_enumTypes[0]
}

func (x REQUEST_STATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use REQUEST_STATE.Descriptor instead.
func (REQUEST_STATE) EnumDescriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{0}
}

type RQUEST_TYPE int32

const (
	RQUEST_TYPE_extra_bin      RQUEST_TYPE = 0
	RQUEST_TYPE_replacement    RQUEST_TYPE = 1
	RQUEST_TYPE_new_bin        RQUEST_TYPE = 2
	RQUEST_TYPE_special_pickup RQUEST_TYPE = 3
)

// Enum value maps for RQUEST_TYPE.
var (
	RQUEST_TYPE_name = map[int32]string{
		0: "extra_bin",
		1: "replacement",
		2: "new_bin",
		3: "special_pickup",
	}
	RQUEST_TYPE_value = map[string]int32{
		"extra_bin":      0,
		"replacement":    1,
		"new_bin":        2,
		"special_pickup": 3,
	}
)

func (x RQUEST_TYPE) Enum() *RQUEST_TYPE {
	p := new(RQUEST_TYPE)
	*p = x
	return p
}

func (x RQUEST_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RQUEST_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_request_proto_enumTypes[1].Descriptor()
}

func (RQUEST_TYPE) Type() protoreflect.EnumType {
	return &file_rpc_request_proto_enumTypes[1]
}

func (x RQUEST_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RQUEST_TYPE.Descriptor instead.
func (RQUEST_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{1}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User          *UserDetails           `protobuf:"bytes,3,opt,name=user,proto3,oneof" json:"user,omitempty"`
	State         REQUEST_STATE          `protobuf:"varint,4,opt,name=state,proto3,enum=pb.REQUEST_STATE" json:"state,omitempty"`
	DateOfDropoff *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_of_dropoff,json=dateOfDropoff,proto3" json:"date_of_dropoff,omitempty"`
	Payment       *Payment               `protobuf:"bytes,6,opt,name=payment,proto3,oneof" json:"payment,omitempty"`
	Bin           *Bin                   `protobuf:"bytes,7,opt,name=bin,proto3,oneof" json:"bin,omitempty"`
	Type          RQUEST_TYPE            `protobuf:"varint,8,opt,name=type,proto3,enum=pb.RQUEST_TYPE" json:"type,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Request) GetUser() *UserDetails {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Request) GetState() REQUEST_STATE {
	if x != nil {
		return x.State
	}
	return REQUEST_STATE_pendingA
}

func (x *Request) GetDateOfDropoff() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfDropoff
	}
	return nil
}

func (x *Request) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *Request) GetBin() *Bin {
	if x != nil {
		return x.Bin
	}
	return nil
}

func (x *Request) GetType() RQUEST_TYPE {
	if x != nil {
		return x.Type
	}
	return RQUEST_TYPE_extra_bin
}

type CreateRequestPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    RQUEST_TYPE            `protobuf:"varint,1,opt,name=type,proto3,enum=pb.RQUEST_TYPE" json:"type,omitempty"`
	BinType *BinType               `protobuf:"varint,2,opt,name=bin_type,json=binType,proto3,enum=pb.BinType,oneof" json:"bin_type,omitempty"`
	Date    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3,oneof" json:"date,omitempty"`
}

func (x *CreateRequestPayload) Reset() {
	*x = CreateRequestPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestPayload) ProtoMessage() {}

func (x *CreateRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestPayload.ProtoReflect.Descriptor instead.
func (*CreateRequestPayload) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequestPayload) GetType() RQUEST_TYPE {
	if x != nil {
		return x.Type
	}
	return RQUEST_TYPE_extra_bin
}

func (x *CreateRequestPayload) GetBinType() BinType {
	if x != nil && x.BinType != nil {
		return *x.BinType
	}
	return BinType_large
}

func (x *CreateRequestPayload) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type CreateRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data       *Request `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	PaymentUrl string   `protobuf:"bytes,2,opt,name=paymentUrl,proto3" json:"paymentUrl,omitempty"`
}

func (x *CreateRequestResponse) Reset() {
	*x = CreateRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestResponse) ProtoMessage() {}

func (x *CreateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateRequestResponse) Descriptor() ([]byte, []int) {
	return file_rpc_request_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequestResponse) GetData() *Request {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateRequestResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

var File_rpc_request_proto protoreflect.FileDescriptor

var file_rpc_request_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x62, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd7,
	0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x48, 0x00, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6f,
	0x66, 0x5f, 0x64, 0x72, 0x6f, 0x70, 0x6f, 0x66, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x66, 0x44, 0x72, 0x6f, 0x70, 0x6f, 0x66, 0x66, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x01, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x03, 0x62, 0x69, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x6e, 0x48, 0x02, 0x52, 0x03,
	0x62, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x62, 0x69, 0x6e, 0x22, 0xb3, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x62, 0x69, 0x6e, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x07, 0x62, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x01, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x62, 0x69, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x22, 0x58,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x2a, 0x36, 0x0a, 0x0d, 0x52, 0x45, 0x51, 0x55,
	0x45, 0x53, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x12, 0x0c, 0x0a, 0x08, 0x70, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x41, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x02,
	0x2a, 0x4e, 0x0a, 0x0b, 0x52, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12,
	0x0d, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x62, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x5f, 0x62, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x10, 0x03,
	0x42, 0x1a, 0x5a, 0x18, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2d, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x2f,
	0x77, 0x61, 0x73, 0x74, 0x65, 0x2d, 0x62, 0x69, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_request_proto_rawDescOnce sync.Once
	file_rpc_request_proto_rawDescData = file_rpc_request_proto_rawDesc
)

func file_rpc_request_proto_rawDescGZIP() []byte {
	file_rpc_request_proto_rawDescOnce.Do(func() {
		file_rpc_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_request_proto_rawDescData)
	})
	return file_rpc_request_proto_rawDescData
}

var file_rpc_request_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rpc_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_request_proto_goTypes = []interface{}{
	(REQUEST_STATE)(0),            // 0: pb.REQUEST_STATE
	(RQUEST_TYPE)(0),              // 1: pb.RQUEST_TYPE
	(*Request)(nil),               // 2: pb.Request
	(*CreateRequestPayload)(nil),  // 3: pb.CreateRequestPayload
	(*CreateRequestResponse)(nil), // 4: pb.CreateRequestResponse
	(*UserDetails)(nil),           // 5: pb.UserDetails
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*Payment)(nil),               // 7: pb.Payment
	(*Bin)(nil),                   // 8: pb.Bin
	(BinType)(0),                  // 9: pb.BinType
}
var file_rpc_request_proto_depIdxs = []int32{
	5,  // 0: pb.Request.user:type_name -> pb.UserDetails
	0,  // 1: pb.Request.state:type_name -> pb.REQUEST_STATE
	6,  // 2: pb.Request.date_of_dropoff:type_name -> google.protobuf.Timestamp
	7,  // 3: pb.Request.payment:type_name -> pb.Payment
	8,  // 4: pb.Request.bin:type_name -> pb.Bin
	1,  // 5: pb.Request.type:type_name -> pb.RQUEST_TYPE
	1,  // 6: pb.CreateRequestPayload.type:type_name -> pb.RQUEST_TYPE
	9,  // 7: pb.CreateRequestPayload.bin_type:type_name -> pb.BinType
	6,  // 8: pb.CreateRequestPayload.date:type_name -> google.protobuf.Timestamp
	2,  // 9: pb.CreateRequestResponse.data:type_name -> pb.Request
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_rpc_request_proto_init() }
func file_rpc_request_proto_init() {
	if File_rpc_request_proto != nil {
		return
	}
	file_user_proto_init()
	file_bin_proto_init()
	file_payment_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRequestPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rpc_request_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_rpc_request_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_request_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_request_proto_goTypes,
		DependencyIndexes: file_rpc_request_proto_depIdxs,
		EnumInfos:         file_rpc_request_proto_enumTypes,
		MessageInfos:      file_rpc_request_proto_msgTypes,
	}.Build()
	File_rpc_request_proto = out.File
	file_rpc_request_proto_rawDesc = nil
	file_rpc_request_proto_goTypes = nil
	file_rpc_request_proto_depIdxs = nil
}
